### ISSUE TITLE
Feature request: cleanup of vk.com image cache

### ISSUE THREAD

**Issue by Self-Perfection** [mentaljam/harbour-mashka#4]
Apparently Sailfish OS does not ever cleanup images that are leftover from vk event feed integration. These images are invisible for ordinary user and cannot be deleted without root access. Seems reasonable to add cleanup of this cache to mashka.

For more info see https://together.jolla.com/question/195374/huge-images-cache-for-vkcom-account

**Comment by mentaljam** [comment]
This feature doesn't quite match the original idea of Mashka - delete data left by removed applications. So adding such a feature requires some reformation of Mashka (which was already started as a [separate project](https://github.com/mentaljam/harbour-shipyard)). The bad thing is that I don't have enough free time to implement it. But both the projects are open for PR :)

Also it is a question how to implement such a feature (which requires root access as you mentioned) and keep Mashka Harbour-allowed.

**Comment by Olf0** [comment]
@Self-Perfection, I was surprised to see that I was the one (by [a comment at TJC](https://together.jolla.com/question/195374/huge-images-cache-for-vkcom-account/)) who suggested to file this suggestion for Mashka.

After re-reading the whole story, I must admit that:
* I concur with your statement in [a comment at TJC](https://together.jolla.com/question/195374/huge-images-cache-for-vkcom-account/):
  <sub>*I'm quite sure that the bug is not in [vk.com](http://vk.com/) website, but in SailfishOS integration. More precisely in "Settings -> Accounts -> VK -> Download -> Feeds and notification" feature. Images from feeds are stored indefinitely without any visible indication and any way for ordinary user to clear them.*</sub>
* Mashka was unmaintained for a quite a while.  Although I am planning to revive it, I do not plan to alter its focus on detecting left behind data and offering the user of a device to remove it.
  * Any automatic removal mechanism is clearly beyond Mashka's feature set, but you did not ask for that in the suggestion posted here, only in [the original report at TJC](https://together.jolla.com/question/195374/huge-images-cache-for-vkcom-account/).
  * To remove anything which is not deletable from the context of the (primary) user is out of scope, since that would prevent submitting Mashka to the Jolla Store; but this is one goal of reviving Mashka, otherwise its extant, outdated releases in the Jolla Store would stay being the most recent ones.

I suggest to first check, if the issue is still exactly the same as it was five years ago.  AFAIR and AFAICS the SailfishOS's settings app is proprietary, hence not in one of [the SailfishOS repositories](https://github.com/sailfishos) here at GitHub (you might want to double-check), where one could file an issue report.  Thus an issue report ought to be [filed at FSO](https://forum.sailfishos.org/) by using the "**+** New Topic*"-button, choosing the category "Bug report" and diligently filling out the issue template, plus adding a descriptive, concise title.

@self-perfection, is it O.K. for you to close this issue here?
<br />

P.S.: @mentaljam mentioned the app [Shipyard](https://github.com/mentaljam/harbour-shipyard) he began to write six years ago as a much better and more sophisticated implementation of a similar feature set than Maska, but Shipyard also aims at adhering to the Jolla Store guidelines, so it is unsuitable to address this issue, too.  Note that Shipyard has never seen a release and is even longer unmaintained than Mashka.

Last resort would be to create a timer unit for systemd which calls `find` [as already suggested](https://together.jolla.com/question/195374/huge-images-cache-for-vkcom-account/?answer=198233#post-id-198233), maybe using a few more options for `find`.  This and its packaging to an RPM file could be hosted at GitHub, GitLab or Codeberg to allow for everybody to contribute.

**Comment by Self-Perfection** [comment]
It's OK for me to close this feature request here.

I can not check if the issue is still here as I do not use devices with SailfishOS anymore. I hope it was fixed.
